---
version: "3.4"
services:
  frontend:
    build:
      context: .
      args:
        # set build arg from environment variable with same name
        # add default to squelch warnings
        VITE_VERSION_STRING: ${VITE_VERSION_STRING:-local}

    ports:
      # allow override of published port
      - ${P_PORT:-8000}:80
    env_file:
      # Reuse .env from CRA
      - .env
